name: 'Living Documentation Generator'
description: 'Generates living documentation from current state of user defined GitHub repositories.'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token for authentication.'
    required: true
  repositories:
    description: 'JSON string defining the repositories to be included in the documentation generation.'
    required: true
  project-state-mining:
    description: 'Enable or disable mining of project state data.'
    required: false
    default: 'false'
  verbose-logging:
    description: 'Enable or disable verbose logging.'
    required: false
    default: 'false'
  output-path:
    description: 'Path to the generated living documentation files.'
    required: false
    default: './output'
outputs:
  output-path:
    description: 'Path to the generated living documentation files'
    value: ${{ steps.liv-doc-generator.outputs.output-path }}

branding:
  icon: 'book'
  color: 'yellow'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v5.1.1
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Set PROJECT_ROOT and update PYTHONPATH
      run: |
        ACTION_ROOT="${{ github.action_path }}"
        export PYTHONPATH="${PYTHONPATH}:${ACTION_ROOT}/living-doc-generator"
      shell: bash

    - name: Call Living Documentation Generator
      id: liv-doc-generator
      env:
        INPUT_GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        INPUT_REPOSITORIES: ${{ inputs.repositories }}
        INPUT_PROJECT_STATE_MINING: ${{ inputs.project_state_mining }}
        INPUT_VERBOSE_LOGGING: ${{ inputs.verbose-logging }}
        INPUT_OUTPUT_PATH: ${{ inputs.output-path }}

      run: |
        python ${{ github.action_path }}/main.py
      shell: bash
