name: 'Living Documentation Generator - MDOC'
description: 'Generates living documentation in MDOC format'
inputs:
  source:
    description: 'Path to source file containing the data to be processed.'
    required: true
  release:
    description: 'Enable or disable the release filtering.'
    required: false
    default: 'false'
  structured-output:
    description: 'Enable or disable structured output.'
    required: false
    default: 'false'
  report-page:
    description: 'Enable or disable the generation of the report page.'
    required: false
    default: 'false'
  verbose-logging:
    description: 'Enable or disable verbose logging.'
    required: false
    default: 'false'

outputs:
  output-path:
    description: 'Path to the generated living documentation files.'
    value: ${{ steps.liv-doc-generator.outputs.output-path }}

branding:
  icon: 'book'
  color: 'yellow'

runs:
  using: 'composite'
  steps:

    - name: Install Python dependencies
      run: |
        pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Set PROJECT_ROOT and update PYTHONPATH
      run: |
        ACTION_ROOT="${{ github.action_path }}"
        export PYTHONPATH="${PYTHONPATH}:${ACTION_ROOT}/living-doc-generator"
      shell: bash

    - name: Prepare environment variables
      run: |
        echo "INPUT_SOURCE=${{ inputs.source }}" >> $GITHUB_ENV
        echo "INPUT_RELEASE=${{ inputs.release }}" >> $GITHUB_ENV
        echo "INPUT_STRUCTURED_OUTPUT=${{ inputs.structured-output }}" >> $GITHUB_ENV
        echo "INPUT_REPORT_PAGE=${{ inputs.report-page }}" >> $GITHUB_ENV
        echo "INPUT_VERBOSE_LOGGING=${{ inputs.verbose-logging }}" >> $GITHUB_ENV
      shell: bash

    - name: Run Living Documentation Generator for Mdoc
      id: liv-doc-generator
      env:
        INPUT_SOURCE: ${{ env.INPUT_SOURCE }}

        INPUT_RELEASE: ${{ env.INPUT_RELEASE }}
        INPUT_STRUCTURED_OUTPUT: ${{ env.INPUT_STRUCTURED_OUTPUT }}
        INPUT_REPORT_PAGE: ${{ env.INPUT_REPORT_PAGE }}
        INPUT_VERBOSE_LOGGING: ${{ env.INPUT_VERBOSE_LOGGING }}

      run: |
        python ${{ github.action_path }}/main.py
      shell: bash
