name: "Integration tests"

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  IntegrationTests1:
    runs-on: ubuntu-latest
    name: Integration Tests all issues
    steps:
    - name: Integration test
      id: generate_living_doc
      uses: ./
      env:
        GITHUB-TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        liv-doc-regime: true
        liv-doc-repositories: |
          [
            {
              "organization-name": "AbsaOSS",
              "repository-name": "living-doc-generator",
              "query-labels": ["int-tests"],
              "projects-title-filter": [] 
            }
          ]

    - name: Set up Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Verify integration test results
      run: pytest tests/integration

  IntegrationTests2:
    runs-on: ubuntu-latest
    name: Integration Tests in project
    steps:
      - name: Integration test
        id: generate_living_doc
        uses: ./
        env:
          GITHUB-TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          liv-doc-regime: true
          liv-doc-repositories: |
            [
              {
                "organization-name": "AbsaOSS",
                "repository-name": "living-doc-generator",
                "query-labels": ["int-tests"],
                "projects-title-filter": ["integration-tests-for-living-doc-generator"] 
              }
            ]

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Verify integration test results
        run: pytest tests/integration