name: "Integration tests"

on:
  push:
    branches: [ "master" ]

jobs:
  python-tests:
    runs-on: ubuntu-latest
    name: Python Tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests with Pytest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pytest tests/integration
