name: "Static analysis & tests"

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  analysis:
    runs-on: ubuntu-latest
    name: Pylint Analysis
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.5

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pylint

      - name: Analysing the code with pylint
        run: |
          pylint \
            --fail-under=6.0 \
            --ignore-patterns=test_.*?py \
            --max-line-length=180 \
            $(git ls-files '*.py')  

  python-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.5

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install coverage pytest

      - name: Run tests
        run: coverage run --source='similarity,column2Vec' -m pytest ./test

      - name: Show coverage
        run: coverage report -m

      - name: Create coverage file
        run: coverage xml

      - name: Get Cover
        uses: orgoro/coverage@v3.1
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          thresholdAll: 0.7
          thresholdNew: 0.9
